name: Auto Add PRs to Project

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC (adjust as needed)
  workflow_dispatch: # Allow manual runs

jobs:
  add-prs-to-project:
    runs-on: ubuntu-latest

    steps:
    - name: Search PRs Matching Query
      id: search-prs
      uses: actions/github-script@v6
      with:
        script: |
          const query = "sort:created-asc is:pr is:open author:jackfrancis author:dtzar author:willie-yao author:mboersma author:jont828 author:nawazkh author:marosset repo:kubernetes-sigs/cluster-api-provider-azure repo:kubernetes-sigs/cluster-api repo:kubernetes-sigs/image-builder repo:kubernetes/autoscaler repo:kubernetes/enhancements repo:kubernetes/kubernetes repo:Azure/aks-engine repo:kubernetes-sigs/cloud-provider-azure repo:kubernetes/perf-tests repo:kubernetes/test-infra repo:Azure/azure-capi-cli-extension";
          const results = await github.search.issuesAndPullRequests({ q: query });
          core.setOutput('prs', JSON.stringify(results.data.items));

    - name: Add PRs to Project
      uses: actions/github-script@v6
      with:
        script: |
          const prs = JSON.parse(core.getInput('prs'));
          const projectId = "PVT_kwHOCAOYJ84AtKVY"; # Replace with your project ID

          for (const pr of prs) {
            await github.projects.addProjectCard({
              project_id: projectId,
              content_id: pr.id,
              content_type: "PullRequest"
            });
          }
