name: Auto Add PRs to Project

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC (adjust as needed)
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual runs

jobs:
  add-prs-to-project:
    runs-on: ubuntu-latest

    steps:
    - name: Search PRs Matching Query
      id: search-prs
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.PROJECT_TOKEN }}
        script: |
          const query = "sort:created-asc is:pr is:open author:jackfrancis author:dtzar author:willie-yao author:mboersma author:jont828 author:nawazkh author:marosset repo:kubernetes-sigs/cluster-api-provider-azure repo:kubernetes-sigs/cluster-api repo:kubernetes-sigs/image-builder repo:kubernetes/autoscaler repo:kubernetes/enhancements repo:kubernetes/kubernetes repo:Azure/aks-engine repo:kubernetes-sigs/cloud-provider-azure repo:kubernetes/perf-tests repo:kubernetes/test-infra repo:Azure/azure-capi-cli-extension"
          const results = await github.rest.search.issuesAndPullRequests({ q: query })
          const prs = JSON.stringify(results.data.items)
          const queryproject = `mutation AddProjectV2ItemById($projectId: ID!, contentId: pr.node_id) {addProjectV2ItemById(input: {projectId: $projectId) {item {id}}}`;
          const variables = {
            projectId: 'PVT_kwHOCAOYJ84AtKVY'
          }
          for (const pr of prs) {
           console.log(pr.node_id)
           await github.graphql(queryproject, variables)
          }
          //console.log(prs)
          //core.setOutput('prs', JSON.stringify(results.data.items));
          //console.log(JSON.stringify(results.data.items))
          //console.log(${{ steps.search-prs.outputs.prs }})
